---
# This playbook contains common plays that will be run on all nodes.

- name: update apt packages
  command: /usr/bin/apt-get update

- name: installing tools and utility packages
  apt: pkg={{ item }} state=latest
  with_items:
    - wget
    - vim-nox
    - python-dev
    - python-setuptools
    - python-pip
    - htop
    - libbz2-dev
    - zlib1g-dev
    - libfreetype6-dev
    - libjpeg62-dev
    - liblcms1-dev
    - libssl-dev
    - libbluetooth-dev
    - unzip

- name: install python libraries
  pip: name={{ item }}
  with_items:
    - pil
    - yolk

